<?php

namespace Clicproxy\PolleetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PollAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollAnswerRepository extends EntityRepository
{
}
